//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaShop.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageComment
    {
        public int CommentID { get; set; }
        public int PageID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> ShowInPage { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
